part of 'expression.dart';

/// Returns a list of all the variables in the expression.
final defaultContext = {
  // Constants
  'pi': pi,
  'e': e,
  'ex': ex,
  'tau': tau,
  'ln2': ln2,
  'ln10': ln10,
  'log2e': log2e,
  'log10e': log10e,
  'sqrt1_2': sqrt1_2,
  'sqrt2': sqrt2,
  'sqrt3': sqrt3,

  // Basic Math functions
  'abs': abs,
  'sqrt': sqrt,
  'cbrt': cbrt,
  'nthRoot': nthRoot,
  'exp': exp,
  'pow': pow,
  'logBase': logBase,
  'log10': log10,
  'log': log,
  'ln': log,
  'factorial': factorial,
  'factorial2': factorial2,
  'doubleFactorial': doubleFactorial,
  'step': step,
  'rect': rect,
  'sign': sign,
  'modF': modF,
  'mod': mod,
  'modInv': (num a, num m) => modInv(a, m),
  'nChooseRModPrime': nChooseRModPrime,
  'bigIntNChooseRModPrime': bigIntNChooseRModPrime,
  'floor': floor,
  'ceil': ceil,
  'hypot': hypot,
  'round': round,
  'roundDecimal': (num x, int n) => round(x, n),
  'roundTo': (num x, int n) => round(x, n),
  'clamp': clamp,
  'lerp': lerp,
  'rec': rec,
  'pol': pol,
  'isDigit': isDigit,
  'isAlpha': isAlpha,
  'isAlphaNumeric': isAlphaNumeric,
  'isDivisible': isDivisible,
  'isEven': isEven,
  'isOdd': isOdd,
  'isPrime': isPrime,
  'nthPrime': nthPrime,
  'sieve': sieve,
  'fibonacci': fib,
  'fib': fib,
  'isPerfectSquare': isPerfectSquare,
  'isPerfectCube': isPerfectCube,
  'isFibonacci': isFibonacci,
  'isPalindrome': isPalindrome,
  'isPandigital': isPandigital,
  'isArmstrongNumber': isArmstrongNumber,
  'isPerfectNumber': isPerfectNumber,
  'trunc': trunc,
  'factors': factors,
  'factorsOf': factors,
  'primeFactors': primeFactors,
  'nthTriangleNumber': nthTriangleNumber,
  'nthPentagonalNumber': nthPentagonalNumber,
  'nthHexagonalNumber': nthHexagonalNumber,
  'nthTetrahedralNumber': nthTetrahedralNumber,
  'nthHarmonicNumber': nthHarmonicNumber,
  'gamma': gamma,

  //Polynomials
  'roots': (dynamic exp) => Polynomial.fromString(exp.toString()).roots(),

  // Calculus functions
  'derivative': (dynamic exp) =>
      Expression.parse(exp.toString()).differentiate(),
  'integrate': (dynamic exp) => Expression.parse(exp.toString()).integrate(),
  'simplify': (dynamic exp) => Expression.parse(exp.toString()).simplify(),

  // Trigonometric functions
  'sin': (num x) => sin(degToRad(x)),
  'cos': (num x) => cos(degToRad(x)),
  'tan': (num x) => tan(degToRad(x)),
  'csc': (num x) => csc(degToRad(x)),
  'sec': (num x) => sec(degToRad(x)),
  'cot': (num x) => cot(degToRad(x)),
  'asin': (num x) => radToDeg(asin(x)),
  'acos': (num x) => radToDeg(acos(x)),
  'atan': (num x) => radToDeg(atan(x)),
  'atan2': (num x, num y) => radToDeg(atan2(x, y)),
  'asec': (num x) => radToDeg(asec(x)),
  'acsc': (num x) => radToDeg(acsc(x)),
  'acot': (num x) => radToDeg(acot(x)),
  'sinh': sinh,
  'cosh': cosh,
  'tanh': tanh,
  'csch': csch,
  'sech': sech,
  'coth': coth,
  'asinh': asinh,
  'acosh': acosh,
  'atanh': atanh,
  'acsch': acsch,
  'asech': asech,
  'acoth': acoth,
  'vers': vers,
  'covers': covers,
  'havers': havers,
  'exsec': exsec,
  'excsc': excsc,
  'sawtooth': sawtooth,
  'squareWave': squareWave,
  'triangleWave': triangleWave,

  // Statistic functions
  'avg': avg,
  'max': max,
  'min': min,
  'sum': sum,
  'sumTo': (num x) => sumTo(x.toInt()),
  'nPr': (num n, int r) => permutations(n, r).length,
  'permutations': (num n, int r) => permutations(n, r).length,
  'nCr': (num n, int r) => combinations(n, r).length,
  'combinations': (num n, int r) => combinations(n, r).length,

  'mean': mean,
  'median': median,
  'mode': mode,
  'variance': variance,
  'standardDeviation': stdDev,
  'stdDev': stdDev,
  'stdErrMean': stdErrMean,
  'tValue': tValue,
  'quartiles': quartiles,
  'gcf': gcf,
  'gcd': gcd,
  'lcm': lcm,

  // String functions
  'string': (dynamic x) => x.toString(),
  'length': (dynamic x) => x.toString().length,
  'toUpper': (dynamic x) => x.toString().toUpperCase(),
  'toLower': (dynamic x) => x.toString().toLowerCase(),
  'concat': (dynamic x, dynamic y) => x.toString() + y.toString(),
  'link': (dynamic x, dynamic y) => '<a href="$y">$x</a>',
  'str2number': (dynamic x) => num.parse(x.toString()),
  'number2str': (dynamic x) => x.toString(),
  'left': (dynamic x, dynamic y) => x.toString().substring(0, y.toInt()),
  'right': (dynamic x, dynamic y) => x.toString().substring(y.toInt()),
  'number': (dynamic x) => num.parse(x.toString()),

  // Date functions
  'now': DateTime.now().toString(),
  'daysDiff': (dynamic x, dynamic y) =>
      DateTime.parse(x).difference(DateTime.parse(y)).inDays,
  'hoursDiff': (dynamic x, dynamic y) =>
      DateTime.parse(x).difference(DateTime.parse(y)).inHours,
  'minutesDiff': (dynamic x, dynamic y) =>
      DateTime.parse(x).difference(DateTime.parse(y)).inMinutes,
  'secondsDiff': (dynamic x, dynamic y) =>
      DateTime.parse(x).difference(DateTime.parse(y)).inSeconds,
  'millisecondsDiff': (dynamic x, dynamic y) =>
      DateTime.parse(x).difference(DateTime.parse(y)).inMilliseconds,
  'microsecondsDiff': (dynamic x, dynamic y) =>
      DateTime.parse(x).difference(DateTime.parse(y)).inMicroseconds,
};
