part of '../geometry.dart';

/// A class representing a torus (donut shape) in 3D space.
///
/// A torus is a surface of revolution generated by revolving a circle
/// in 3D space about an axis coplanar with the circle.
///
/// Properties:
/// - Major radius R (from center of torus to center of tube)
/// - Minor radius r (radius of the tube)
/// - Volume = 2π²Rr²
/// - Surface Area = 4π²Rr
///
/// Example:
/// ```dart
/// var torus = Torus(majorRadius: 5, minorRadius: 2);
/// print('Volume: ${torus.volume()}');
/// ```
class Torus extends SolidGeometry {
  /// The center point of the torus.
  Point center;

  /// Major radius (from center of torus to center of tube).
  double majorRadius;

  /// Minor radius (radius of the tube).
  double minorRadius;

  /// Creates a torus with specified radii.
  ///
  /// [majorRadius] and [minorRadius] must be positive.
  /// [majorRadius] should be greater than [minorRadius].
  /// [center] defaults to (0, 0, 0).
  Torus({required this.majorRadius, required this.minorRadius, Point? center})
      : center = center ?? Point(0, 0, 0),
        super('Torus') {
    if (majorRadius <= 0 || minorRadius <= 0) {
      throw ArgumentError(
          'Radii must be positive. Got major: $majorRadius, minor: $minorRadius');
    }
    if (majorRadius < minorRadius) {
      throw ArgumentError(
          'Major radius must be greater than minor radius. Got major: $majorRadius, minor: $minorRadius');
    }
  }

  /// Creates a torus from volume and major radius.
  ///
  /// Calculates minor radius from: r = √(V / (2π²R))
  ///
  /// Example:
  /// ```dart
  /// var torus = Torus.fromVolumeAndMajorRadius(volume: 100, majorRadius: 5);
  /// ```
  factory Torus.fromVolumeAndMajorRadius({
    required double volume,
    required double majorRadius,
    Point? center,
  }) {
    if (volume <= 0) throw ArgumentError('Volume must be positive');
    if (majorRadius <= 0) throw ArgumentError('Major radius must be positive');

    double minorRadius = sqrt(volume / (2 * pi * pi * majorRadius));
    return Torus(
        majorRadius: majorRadius, minorRadius: minorRadius, center: center);
  }

  /// Creates a torus from volume and minor radius.
  ///
  /// Calculates major radius from: R = V / (2π²r²)
  ///
  /// Example:
  /// ```dart
  /// var torus = Torus.fromVolumeAndMinorRadius(volume: 100, minorRadius: 2);
  /// ```
  factory Torus.fromVolumeAndMinorRadius({
    required double volume,
    required double minorRadius,
    Point? center,
  }) {
    if (volume <= 0) throw ArgumentError('Volume must be positive');
    if (minorRadius <= 0) throw ArgumentError('Minor radius must be positive');

    double majorRadius = volume / (2 * pi * pi * minorRadius * minorRadius);
    return Torus(
        majorRadius: majorRadius, minorRadius: minorRadius, center: center);
  }

  /// Creates a torus from surface area and major radius.
  ///
  /// Calculates minor radius from: r = A / (4π²R)
  ///
  /// Example:
  /// ```dart
  /// var torus = Torus.fromSurfaceAreaAndMajorRadius(surfaceArea: 200, majorRadius: 5);
  /// ```
  factory Torus.fromSurfaceAreaAndMajorRadius({
    required double surfaceArea,
    required double majorRadius,
    Point? center,
  }) {
    if (surfaceArea <= 0) throw ArgumentError('Surface area must be positive');
    if (majorRadius <= 0) throw ArgumentError('Major radius must be positive');

    double minorRadius = surfaceArea / (4 * pi * pi * majorRadius);
    return Torus(
        majorRadius: majorRadius, minorRadius: minorRadius, center: center);
  }

  /// Creates a torus from surface area and minor radius.
  ///
  /// Calculates major radius from: R = A / (4π²r)
  ///
  /// Example:
  /// ```dart
  /// var torus = Torus.fromSurfaceAreaAndMinorRadius(surfaceArea: 200, minorRadius: 2);
  /// ```
  factory Torus.fromSurfaceAreaAndMinorRadius({
    required double surfaceArea,
    required double minorRadius,
    Point? center,
  }) {
    if (surfaceArea <= 0) throw ArgumentError('Surface area must be positive');
    if (minorRadius <= 0) throw ArgumentError('Minor radius must be positive');

    double majorRadius = surfaceArea / (4 * pi * pi * minorRadius);
    return Torus(
        majorRadius: majorRadius, minorRadius: minorRadius, center: center);
  }

  /// Calculates the volume of the torus.
  ///
  /// Volume = 2π²Rr²
  @override
  double volume() {
    return 2 * pi * pi * majorRadius * minorRadius * minorRadius;
  }

  /// Calculates the surface area of the torus.
  ///
  /// Surface Area = 4π²Rr
  @override
  double surfaceArea() {
    return 4 * pi * pi * majorRadius * minorRadius;
  }

  @override
  double area() => surfaceArea();

  @override
  String toString() {
    return 'Torus(majorRadius: $majorRadius, minorRadius: $minorRadius, volume: ${volume()})';
  }

  @override
  BoundingBox3D boundingBox() {
    double outerRadius = majorRadius + minorRadius;
    return BoundingBox3D(
      Point(center.x - outerRadius, center.y - outerRadius,
          center.z! - minorRadius),
      Point(center.x + outerRadius, center.y + outerRadius,
          center.z! + minorRadius),
    );
  }
}
